name = "DiscretizeDistributions"
uuid = "1dbf0e27-43cd-4e03-8ecf-3f7be9d12b15"
authors = ["GBarnsley <gregbarnsley@hotmail.co.uk>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"

[compat]
Aqua = "0.8"
Distributions = "0.25"
IntervalArithmetic = "0.23, 1"
JET = "0.9, 0.10"
Statistics = "1"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Statistics", "Aqua", "JET"]
